# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 21ac2ddca6d076394f78a79e939f1d547c458c8e1f477b8098b43909f644eef87e38974e2e97ac39708b02515e0bb7af1176fbe6b4269d564f0030b4211de757

test:
  secret_key_base: 68fc0c60d43ceec35db0abe465853f5d7d1568f41b68a0fe463d2ae36abff94c644eb7ebb26dbea6c350fa0baa247f50c0598106970b6d1627f3ee082d6f13f6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
